name: Manual Chocolatey Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from nuspec
        run: |
          $nuspecContent = Get-Content quickdeploy.nuspec -Raw
          $version = [regex]::Match($nuspecContent, '<version>([^<]+)</version>').Groups[1].Value
          Write-Output "Extracted version: $version"
          echo "VERSION=$version" >> $env:GITHUB_ENV
        shell: powershell

      - name: Package and publish to Chocolatey
        run: |
          rm -rf .git
          rm -rf .github
          rm -rf Formula
          choco pack
          choco push quickdeploy.${{ env.VERSION }}.nupkg --source https://push.chocolatey.org/ --api-key ${{ secrets.CHOCOLATEY_API_KEY }}
        shell: powershell
